server:
  port: 8081

spring:
  application:
    name: pms-server
  datasource:
    url: jdbc:mysql://localhost:3306/guli_pms?useOldAliasMetadataBehavior=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# mybatis-plus 配置内容
mybatis-plus:
  configuration:
    #是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto # ID 主键自增
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/pms/**/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity

management:
  endpoints:
    web:
      exposure:
        include: "*"